#########################################
#
#   SCLOG 
#
#########################################
version: '2'

services:
    db:
        build: db
        image: sclogdb
        shm_size: 1024M
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - 3306:3306
            